In [ ]:
import pandas as pd

# Load feature and target datasets
X = pd.read_csv("derm_data.csv")
y = pd.read_csv("derm_target.csv").squeeze() # convert dataframe to 1D array to better fit SVC models

In [ ]:
X.head()

,erythema,scaling,definite-borders,itching,koebner phenomenon,polygonal papules,follicular papules,oral-mucosal involvement,knee elbow involvement,scalp involvement,...,focal hypergranulosis,disappearance of the granular layer,vacuolisation and damage of the basal layer,spongiosis,saw-tooth appearance of retes,follicular horn plug,perifollicular parakeratosis,inflammatory monoluclear infiltrate,band-like infiltrate,age
0,2,2,0,3,0,0,0,0,1,0,...,0,0,0,3,0,0,0,1,0,55.0
1,3,3,3,2,1,0,0,0,1,1,...,0,0,0,0,0,0,0,1,0,8.0
2,2,1,2,3,1,3,0,3,0,0,...,2,0,2,3,2,0,0,2,3,26.0
3,2,2,2,0,0,0,0,0,3,2,...,0,3,0,0,0,0,0,3,0,40.0
4,2,3,2,2,2,2,0,2,0,0,...,2,2,3,2,3,0,0,2,3,45.0

In [ ]:
y.head()

0    2
1    1
2    3
3    1
4    3
Name: class, dtype: int64

In [ ]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 34 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   erythema                                     366 non-null    int64
 1   scaling                                      366 non-null    int64
 2   definite-borders                             366 non-null    int64
 3   itching                                      366 non-null    int64
 4   koebner phenomenon                           366 non-null    int64
 5   polygonal papules                            366 non-null    int64
 6   follicular papules                           366 non-null    int64
 7   oral-mucosal involvement                     366 non-null    int64
 8   knee elbow involvement                       366 non-null    int64
 9   scalp involvement                            366 non-null    int64
 10  family history                               366 non-null    int64
 11  melanin incontinence                         366 non-null    int64
 12  eosinophils in the infiltrate                366 non-null    int64
 13  pnl infiltrate                               366 non-null    int64
 14  fibrosis of the papillary dermis             366 non-null    int64
 15  exocytosis                                   366 non-null    int64
 16  acanthosis                                   366 non-null    int64
 17  hyperkeratosis                               366 non-null    int64
 18  parakeratosis                                366 non-null    int64
 19  clubbing of the rete ridges                  366 non-null    int64
 20  elongation of the rete ridges                366 non-null    int64
 21  thinning of the suprapapillary epidermis     366 non-null    int64
 22  spongiform pustule                           366 non-null    int64
 23  munro microabcess                            366 non-null    int64
 24  focal hypergranulosis                        366 non-null    int64
 25  disappearance of the granular layer          366 non-null    int64
 26  vacuolisation and damage of the basal layer  366 non-null    int64
 27  spongiosis                                   366 non-null    int64
 28  saw-tooth appearance of retes                366 non-null    int64
 29  follicular horn plug                         366 non-null    int64
 30  perifollicular parakeratosis                 366 non-null    int64
 31  inflammatory monoluclear infiltrate          366 non-null    int64
 32  band-like infiltrate                         366 non-null    int64
 33  age                                          358 non-null    float64
dtypes: float64(1), int64(33)
memory usage: 97.3 KB

In [ ]:
y.info()

<class 'pandas.core.series.Series'>
RangeIndex: 366 entries, 0 to 365
Series name: class
Non-Null Count  Dtype
--------------  -----
366 non-null    int64
dtypes: int64(1)
memory usage: 3.0 KB

.info() showed that all varibles are non-null other than 8 null age values, consistant with the information provided at the dataset sorce website.

In [ ]:
# Fill missing age values with the median to preserve distribution while avoiding NaNs
X['age'].fillna(X['age'].median(), inplace=True)

/tmp/ipykernel_3135/3336523914.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X['age'].fillna(X['age'].median(), inplace=True)

In [ ]:
from sklearn.preprocessing import StandardScaler

# Scale all features for better compatibility with SVM models
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
# Keep as a Dataframe
X_scaled = pd.DataFrame(X_scaled, columns=X.columns)

In [ ]:
# Preview data after scaling
print(X_scaled.head()) # scaled
print(y.head()) # unchanged

   erythema   scaling  definite-borders   itching  koebner phenomenon  \
0 -0.102895  0.292503         -1.709375  1.437334           -0.699049
1  1.403482  1.719916          1.600843  0.557628            0.403761
2 -0.102895 -1.134911          0.497437  1.437334            0.403761
3 -0.102895  0.292503          0.497437 -1.201784           -0.699049
4 -0.102895  1.719916          0.497437  0.557628            1.506571

   polygonal papules  follicular papules  oral-mucosal involvement  \
0          -0.468702           -0.292496                 -0.452637
1          -0.468702           -0.292496                 -0.452637
2           2.669312           -0.292496                  3.148777
3          -0.468702           -0.292496                 -0.452637
4           1.623308           -0.292496                  1.948306

   knee elbow involvement  scalp involvement  ...  focal hypergranulosis  \
0                0.392453          -0.574000  ...              -0.463831
1                0.392453           0.531705  ...              -0.463831
2               -0.626255          -0.574000  ...               1.893978
3                2.429870           1.637410  ...              -0.463831
4               -0.626255          -0.574000  ...               1.893978

   disappearance of the granular layer  \
0                            -0.537770
1                            -0.537770
2                            -0.537770
3                             2.935592
4                             1.777805

   vacuolisation and damage of the basal layer  spongiosis  \
0                                    -0.478502    1.813219
1                                    -0.478502   -0.844878
2                                     1.618885    1.813219
3                                    -0.478502   -0.844878
4                                     2.667578    0.927187

   saw-tooth appearance of retes  follicular horn plug  \
0                      -0.475701             -0.230817
1                      -0.475701             -0.230817
2                       1.621970             -0.230817
3                      -0.475701             -0.230817
4                       2.670805             -0.230817

   perifollicular parakeratosis  inflammatory monoluclear infiltrate  \
0                     -0.235125                            -1.194459
1                     -0.235125                            -1.194459
2                     -0.235125                             0.184632
3                     -0.235125                             1.563724
4                     -0.235125                             0.184632

   band-like infiltrate       age
0             -0.502215  1.237583
1             -0.502215 -1.867565
2              2.214200 -0.678360
3             -0.502215  0.246578
4              2.214200  0.576913

[5 rows x 34 columns]
0    2
1    1
2    3
3    1
4    3
Name: class, dtype: int64

In [ ]:
# Verify Mean of 0 and Std of 1
X_scaled.describe()

,erythema,scaling,definite-borders,itching,koebner phenomenon,polygonal papules,follicular papules,oral-mucosal involvement,knee elbow involvement,scalp involvement,...,focal hypergranulosis,disappearance of the granular layer,vacuolisation and damage of the basal layer,spongiosis,saw-tooth appearance of retes,follicular horn plug,perifollicular parakeratosis,inflammatory monoluclear infiltrate,band-like infiltrate,age
count,3.660000e+02,3.660000e+02,3.660000e+02,3.660000e+02,3.660000e+02,3.660000e+02,3.660000e+02,3.660000e+02,3.660000e+02,3.660000e+02,...,3.660000e+02,3.660000e+02,3.660000e+02,3.660000e+02,3.660000e+02,3.660000e+02,3.660000e+02,3.660000e+02,3.660000e+02,3.660000e+02
mean,-2.620854e-16,-1.650168e-16,-3.882747e-17,3.882747e-17,-4.853434e-17,-4.853434e-17,8.372174e-17,5.338777e-17,-9.706868e-18,-2.912060e-17,...,4.853434e-18,-7.765494e-17,-1.213358e-17,1.043488e-16,2.184045e-17,-3.397404e-17,-4.368091e-17,3.882747e-17,4.368091e-17,-2.135511e-16
std,1.001369e+00,1.001369e+00,1.001369e+00,1.001369e+00,1.001369e+00,1.001369e+00,1.001369e+00,1.001369e+00,1.001369e+00,1.001369e+00,...,1.001369e+00,1.001369e+00,1.001369e+00,1.001369e+00,1.001369e+00,1.001369e+00,1.001369e+00,1.001369e+00,1.001369e+00,1.001369e+00
min,-3.115648e+00,-2.562324e+00,-1.709375e+00,-1.201784e+00,-6.990489e-01,-4.687015e-01,-2.924961e-01,-4.526367e-01,-6.262552e-01,-5.739998e-01,...,-4.638313e-01,-5.377701e-01,-4.785022e-01,-8.448778e-01,-4.757013e-01,-2.308165e-01,-2.351254e-01,-2.573550e+00,-5.022153e-01,-2.396101e+00
25%,-1.028946e-01,-1.134911e+00,-6.059689e-01,-1.201784e+00,-6.990489e-01,-4.687015e-01,-2.924961e-01,-4.526367e-01,-6.262552e-01,-5.739998e-01,...,-4.638313e-01,-5.377701e-01,-4.785022e-01,-8.448778e-01,-4.757013e-01,-2.308165e-01,-2.351254e-01,-1.194459e+00,-5.022153e-01,-7.444268e-01
50%,-1.028946e-01,2.925027e-01,4.974372e-01,-3.220782e-01,-6.990489e-01,-4.687015e-01,-2.924961e-01,-4.526367e-01,-6.262552e-01,-5.739998e-01,...,-4.638313e-01,-5.377701e-01,-4.785022e-01,-8.448778e-01,-4.757013e-01,-2.308165e-01,-2.351254e-01,1.846324e-01,-5.022153e-01,-8.375705e-02
75%,-1.028946e-01,2.925027e-01,4.974372e-01,5.576279e-01,4.037610e-01,-4.687015e-01,-2.924961e-01,-4.526367e-01,3.924533e-01,5.317051e-01,...,-4.638313e-01,6.200173e-01,-4.785022e-01,9.271868e-01,-4.757013e-01,-2.308165e-01,-2.351254e-01,1.846324e-01,-5.022153e-01,7.751137e-01
max,1.403482e+00,1.719916e+00,1.600843e+00,1.437334e+00,2.609381e+00,2.669312e+00,4.972435e+00,3.148777e+00,2.429870e+00,2.743115e+00,...,3.072882e+00,2.935592e+00,2.667578e+00,1.813219e+00,2.670805e+00,6.438566e+00,5.911724e+00,1.563724e+00,2.214200e+00,2.558922e+00

In [ ]:
# View outcome varible split to determine if stratifying is warrented in train test split
print(y.value_counts())

class
1    112
3     72
2     61
5     52
4     49
6     20
Name: count, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

# Train-test split - #1

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42, stratify=y
)
# Stratify train test split to ensure all classes are balanced in split

In [ ]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(292, 34)
(74, 34)
(292,)
(74,)

## Train Models - First Train_Test_Split

In [ ]:
# Import SVC Model - target data is categorical with labels 1-6
from sklearn.svm import SVC

In [ ]:
# Train first SVC model with a linear kernel and balanced class weight to compensate for class imbalance
svc_linear_1 = SVC(kernel='linear', C=1, class_weight='balanced')
svc_linear_1.fit(X_train, y_train)

SVC(C=1, class_weight='balanced', kernel='linear')

In [ ]:
# Train second SVC model with a polynomial kernel and balanced class weight to compensate for class imbalance
svc_poly_1 = SVC(kernel='poly', C=1.5, gamma=0.5, class_weight='balanced')
svc_poly_1.fit(X_train, y_train)

SVC(C=1.5, class_weight='balanced', gamma=0.5, kernel='poly')

In [ ]:
# Train third SVC model with a RBF kernel and balanced class weight to compensate for class imbalance
svc_rbf_1 = SVC(kernel='rbf', C=0.5, gamma='scale', class_weight='balanced')
svc_rbf_1.fit(X_train, y_train)

SVC(C=0.5, class_weight='balanced')

In [ ]:
# Import metrics libraries
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
)

In [ ]:
# Loop evalation metric print outs

# Define model name:object tuples
models = [
    ("Linear SVM 1", svc_linear_1),
    ("Polynomial SVM 1", svc_poly_1),
    ("RBF SVM 1", svc_rbf_1)
]
# Iterate loop for metrics per model
for name, model in models:
    print(f"\n=== {name} ===")
    y_pred = model.predict(X_test)

    # Accuracy
    print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")

    # Classification Report
    print("\nClassification Report:")
    print(classification_report(y_test, y_pred))

    # Confusion Matrix
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, y_pred))

=== Linear SVM 1 ===
Accuracy: 0.9730

Classification Report:
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        23
           2       1.00      0.83      0.91        12
           3       1.00      1.00      1.00        15
           4       0.83      1.00      0.91        10
           5       1.00      1.00      1.00        10
           6       1.00      1.00      1.00         4

    accuracy                           0.97        74
   macro avg       0.97      0.97      0.97        74
weighted avg       0.98      0.97      0.97        74

Confusion Matrix:
[[23  0  0  0  0  0]
 [ 0 10  0  2  0  0]
 [ 0  0 15  0  0  0]
 [ 0  0  0 10  0  0]
 [ 0  0  0  0 10  0]
 [ 0  0  0  0  0  4]]

=== Polynomial SVM 1 ===
Accuracy: 0.9054

Classification Report:
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        23
           2       1.00      0.67      0.80        12
           3       1.00      0.93      0.97        15
           4       0.59      1.00      0.74        10
           5       1.00      0.90      0.95        10
           6       1.00      0.75      0.86         4

    accuracy                           0.91        74
   macro avg       0.93      0.88      0.89        74
weighted avg       0.94      0.91      0.91        74

Confusion Matrix:
[[23  0  0  0  0  0]
 [ 0  8  0  4  0  0]
 [ 0  0 14  1  0  0]
 [ 0  0  0 10  0  0]
 [ 0  0  0  1  9  0]
 [ 0  0  0  1  0  3]]

=== RBF SVM 1 ===
Accuracy: 0.9595

Classification Report:
              precision    recall  f1-score   support

           1       0.96      1.00      0.98        23
           2       1.00      0.83      0.91        12
           3       1.00      0.93      0.97        15
           4       0.83      1.00      0.91        10
           5       1.00      1.00      1.00        10
           6       1.00      1.00      1.00         4

    accuracy                           0.96        74
   macro avg       0.97      0.96      0.96        74
weighted avg       0.96      0.96      0.96        74

Confusion Matrix:
[[23  0  0  0  0  0]
 [ 0 10  0  2  0  0]
 [ 1  0 14  0  0  0]
 [ 0  0  0 10  0  0]
 [ 0  0  0  0 10  0]
 [ 0  0  0  0  0  4]]

The trained support vector machine (SVM) classification models used linear, polynomial, and RBF kernels on a stratified train-test split of a dermatology dataset. Stratification was applied to ensure that all six target classes were proportionally represented in both the training and testing data.

- The Linear SVM achieved the highest accuracy at 97.30%, correctly classifying nearly all of the 74 test instances. It attained perfect precision and recall (1.00) for classes 1, 3, 5, and 6. Class 2 had a recall of 0.83, with two of its instances misclassified as class 4 — as confirmed by the confusion matrix.

- The Polynomial SVM had a lower accuracy of 90.54%. While precision remained high across most classes, recall for class 2 dropped to 0.67 and for class 6 to 0.75. The confusion matrix shows that the polynomial model had difficulty distinguishing between classes 2 and 4, misclassifying four instances of class 2 as class 4, along with one instance each of classes 3, 5, and 6. These patterns suggest that the polynomial kernel may have overfit the training data or misrepresented certain feature interactions, leading to increased misclassification.

- The RBF SVM achieved an accuracy of 95.95%, performing comparably to the linear model. It demonstrated strong classification across all classes, with minor dips in recall for class 2 (0.83) and class 3 (0.93). Most predictions were correct, and misclassifications were minimal, as shown in the confusion matrix.

In [ ]:
# Perform a new Train-Test split

# Train-test split - #2

X_train2, X_test2, y_train2, y_test2 = train_test_split(
    X_scaled, y, test_size=0.2, random_state=99
)
# Removing the stratification to compare how the models perform with and without it

In [ ]:
print(X_train2.shape)
print(X_test2.shape)
print(y_train2.shape)
print(y_test2.shape)

(292, 34)
(74, 34)
(292,)
(74,)

## Train Models - Second Train_Test_Split (no stratification)

In [ ]:
# Train first SVC model with a linear kernel and balanced class weight to compensate for class imbalance (second train_test_split)
svc_linear_2 = SVC(kernel='linear', C=1, class_weight='balanced')
svc_linear_2.fit(X_train2, y_train2)

SVC(C=1, class_weight='balanced', kernel='linear')

In [ ]:
# Train second SVC model with a polynomial kernel and balanced class weight to compensate for class imbalance (second train_test_split)
svc_poly_2 = SVC(kernel='poly', C=1.5, gamma=0.5, class_weight='balanced')
svc_poly_2.fit(X_train2, y_train2)

SVC(C=1.5, class_weight='balanced', gamma=0.5, kernel='poly')

In [ ]:
# Train third SVC model with a RBF kernel and balanced class weight to compensate for class imbalance (second train_test_split)
svc_rbf_2 = SVC(kernel='rbf', C=0.5, gamma='scale', class_weight='balanced')
svc_rbf_2.fit(X_train2, y_train2)

SVC(C=0.5, class_weight='balanced')

In [ ]:
# Loop evalation metric print outs

# Define model name:object tuples
models2 = [
    ("Linear SVM 2", svc_linear_2),
    ("Polynomial SVM 2", svc_poly_2),
    ("RBF SVM 2", svc_rbf_2)
]
# Iterate loop for metrics per model
for name, model in models2:
    print(f"\n=== {name} ===")
    y_pred2 = model.predict(X_test2)

    # Accuracy
    print(f"Accuracy: {accuracy_score(y_test2, y_pred2):.4f}")

    # Classification Report
    print("\nClassification Report:")
    print(classification_report(y_test2, y_pred2))

    # Confusion Matrix
    print("Confusion Matrix:")
    print(confusion_matrix(y_test2, y_pred2))

=== Linear SVM 2 ===
Accuracy: 0.9865

Classification Report:
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        23
           2       0.89      1.00      0.94         8
           3       1.00      1.00      1.00        18
           4       1.00      0.92      0.96        12
           5       1.00      1.00      1.00        13

    accuracy                           0.99        74
   macro avg       0.98      0.98      0.98        74
weighted avg       0.99      0.99      0.99        74

Confusion Matrix:
[[23  0  0  0  0]
 [ 0  8  0  0  0]
 [ 0  0 18  0  0]
 [ 0  1  0 11  0]
 [ 0  0  0  0 13]]

=== Polynomial SVM 2 ===
Accuracy: 0.9730

Classification Report:
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        23
           2       0.88      0.88      0.88         8
           3       1.00      1.00      1.00        18
           4       0.92      0.92      0.92        12
           5       1.00      1.00      1.00        13

    accuracy                           0.97        74
   macro avg       0.96      0.96      0.96        74
weighted avg       0.97      0.97      0.97        74

Confusion Matrix:
[[23  0  0  0  0]
 [ 0  7  0  1  0]
 [ 0  0 18  0  0]
 [ 0  1  0 11  0]
 [ 0  0  0  0 13]]

=== RBF SVM 2 ===
Accuracy: 0.9865

Classification Report:
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        23
           2       0.89      1.00      0.94         8
           3       1.00      1.00      1.00        18
           4       1.00      0.92      0.96        12
           5       1.00      1.00      1.00        13

    accuracy                           0.99        74
   macro avg       0.98      0.98      0.98        74
weighted avg       0.99      0.99      0.99        74

Confusion Matrix:
[[23  0  0  0  0]
 [ 0  8  0  0  0]
 [ 0  0 18  0  0]
 [ 0  1  0 11  0]
 [ 0  0  0  0 13]]

In [ ]:
# The Confusion Matrices only showed 5x5, when there were 6 classes of target variables
# Checking the counts of y_test2 indicated that class 6 did not make it into the test set due to the removal of stratification
print(y_test2.value_counts())

class
1    23
3    18
5    13
4    12
2     8
Name: count, dtype: int64

In the second train-test split, there was no stratification in order to evaluate how the models would perform under naturally imbalanced class distributions. While all three SVM models performed slightly better on this split, the improvement is skewed because class 6 was not captured in the test set, which simplified the classification task and reduced opportunities for misclassification.

- The Linear SVM achieved 98.65% accuracy and nearly perfect performance. Precision and recall were 1.00 for most classes. Class 4 had a small drop in recall (0.92), and class 2’s precision dipped slightly to 0.89 due to one false positive.

- The Polynomial SVM achieved 97.30% accuracy. The model was strong overall, but slightly less reliable. Class 2 showed balanced but lower precision and recall (0.88 each), and class 4 also had a minor drop to 0.92 but misclassifications were minimal.

- The RBF SVM  achieved 98.65% accuracy and matched the Linear model almost exactly. Minor recall loss for class 4 (0.92), but otherwise showed excellent class separation. There were no major misclassifications observed.

These results demonstrate how excluding rare classes (like class 6) can boost metrics without truly improving model generalization. This reinforced the value of stratified sampling in performance evaluation and led me to do one additional train-test split with a different random_state and reintroducing stratification.

---

In [ ]:
# Train-test split - #3

X_train3, X_test3, y_train3, y_test3 = train_test_split(
    X_scaled, y, test_size=0.2, random_state=28, stratify=y
)

In [ ]:
print(X_train3.shape)
print(X_test3.shape)
print(y_train3.shape)
print(y_test3.shape)

(292, 34)
(74, 34)
(292,)
(74,)

In [ ]:
# Check immediately that all classes are represented
print(y_test3.value_counts())

class
1    23
3    15
2    12
5    10
4    10
6     4
Name: count, dtype: int64

In [ ]:
# Train first SVC model with a linear kernel and balanced class weight to compensate for class imbalance (third train_test_split)
svc_linear_3 = SVC(kernel='linear', C=1, class_weight='balanced')
svc_linear_3.fit(X_train3, y_train3)

SVC(C=1, class_weight='balanced', kernel='linear')

In [ ]:
# Train second SVC model with a polynomial kernel and balanced class weight to compensate for class imbalance (third train_test_split)
svc_poly_3 = SVC(kernel='poly', C=1.5, gamma=0.5, class_weight='balanced')
svc_poly_3.fit(X_train3, y_train3)

SVC(C=1.5, class_weight='balanced', gamma=0.5, kernel='poly')

In [ ]:
# Train third SVC model with a RBF kernel and balanced class weight to compensate for class imbalance (third train_test_split)
svc_rbf_3 = SVC(kernel='rbf', C=0.5, gamma='scale', class_weight='balanced')
svc_rbf_3.fit(X_train3, y_train3)

SVC(C=0.5, class_weight='balanced')

In [ ]:
# Loop evalation metric print outs

# Define model name:object tuples
models3 = [
    ("Linear SVM 3", svc_linear_3),
    ("Polynomial SVM 3", svc_poly_3),
    ("RBF SVM 3", svc_rbf_3)
]
# Iterate loop for metrics per model
for name, model in models3:
    print(f"\n=== {name} ===")
    y_pred3 = model.predict(X_test3)

    # Accuracy
    print(f"Accuracy: {accuracy_score(y_test3, y_pred3):.4f}")

    # Classification Report
    print("\nClassification Report:")
    print(classification_report(y_test3, y_pred3))

    # Confusion Matrix
    print("Confusion Matrix:")
    print(confusion_matrix(y_test3, y_pred3))

=== Linear SVM 3 ===
Accuracy: 0.9459

Classification Report:
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        23
           2       0.83      0.83      0.83        12
           3       1.00      1.00      1.00        15
           4       0.80      0.80      0.80        10
           5       1.00      1.00      1.00        10
           6       1.00      1.00      1.00         4

    accuracy                           0.95        74
   macro avg       0.94      0.94      0.94        74
weighted avg       0.95      0.95      0.95        74

Confusion Matrix:
[[23  0  0  0  0  0]
 [ 0 10  0  2  0  0]
 [ 0  0 15  0  0  0]
 [ 0  2  0  8  0  0]
 [ 0  0  0  0 10  0]
 [ 0  0  0  0  0  4]]

=== Polynomial SVM 3 ===
Accuracy: 0.9189

Classification Report:
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        23
           2       0.71      0.83      0.77        12
           3       1.00      0.93      0.97        15
           4       0.78      0.70      0.74        10
           5       1.00      1.00      1.00        10
           6       1.00      1.00      1.00         4

    accuracy                           0.92        74
   macro avg       0.92      0.91      0.91        74
weighted avg       0.92      0.92      0.92        74

Confusion Matrix:
[[23  0  0  0  0  0]
 [ 0 10  0  2  0  0]
 [ 0  1 14  0  0  0]
 [ 0  3  0  7  0  0]
 [ 0  0  0  0 10  0]
 [ 0  0  0  0  0  4]]

=== RBF SVM 3 ===
Accuracy: 0.9595

Classification Report:
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        23
           2       0.91      0.83      0.87        12
           3       1.00      1.00      1.00        15
           4       0.82      0.90      0.86        10
           5       1.00      1.00      1.00        10
           6       1.00      1.00      1.00         4

    accuracy                           0.96        74
   macro avg       0.95      0.96      0.95        74
weighted avg       0.96      0.96      0.96        74

Confusion Matrix:
[[23  0  0  0  0  0]
 [ 0 10  0  2  0  0]
 [ 0  0 15  0  0  0]
 [ 0  1  0  9  0  0]
 [ 0  0  0  0 10  0]
 [ 0  0  0  0  0  4]]

For the third train-test split, stratification was reintroduced to ensure a representative distribution of all 6 target classes in both the training and testing data. This approach aimed to validate earlier results and confirm that each model could generalize well across the full set of classes, including the low-frequency class 6.

- The Linear SVM achieved an accuracy of 94.59% and maintained strong performance overall. Precision and recall were perfect for most classes, but recall for class 2 and class 4 dropped to 0.83 and 0.80, respectively. The confusion matrix shows two instances of class 4 misclassified as class 2 and vice versa, indicating some overlap between these two classes.

- The Polynomial SVM reached an accuracy of 91.89%, which is consistent with its earlier performance. Class 2 had a moderate recall of 0.83, while class 4 dropped further to 0.70. Multiple misclassifications suggest that the polynomial kernel may be overfitting or struggling to separate class boundaries.

- The RBF SVM achieved an accuracy of 95.95%, matching its result from the first stratified split and outperforming the other two models on this split. It showed perfect precision and recall for 4 out of 6 classes, with only minor dips in recall for class 2 (0.83) and class 4 (0.90). The confusion matrix reveals just a few misclassifications, again centered on classes 2 and 4, indicating otherwise solid performance.

These results reaffirm that stratification improves the reliability of model evaluation. It ensures that all classes, especially underrepresented ones like class 6, are properly included in the test set, and it helps uncover areas of confusion between similar classes, as seen between classes 2 and 4.

---

Identify Top 10% Predictive Features

Using 'svc_linear_1' model, the top 10% the most predictive features using the .coef_ attribute will be selected. The linear SVMwas used because only linear models produce directly interpretable feature weights via .coef_. Polynomial and RBF kernels project the data into higher-dimensional spaces, where feature weights cannot be directly interpreted or translated into individual relationships.

In [ ]:
# Get the model coefficients
coefs = svc_linear_1.coef_
coefs

array([[ 5.05252657e-02,  1.02847357e-01,  1.30028511e-01,
         4.61270089e-03,  9.26513531e-02,  0.00000000e+00,
        -1.38777878e-17, -2.77555756e-17,  2.33316639e-01,
         3.99223049e-02,  9.35432867e-03,  0.00000000e+00,
        -7.44402045e-02,  2.66164388e-02, -1.38777878e-17,
        -1.30323843e-01,  4.08267874e-02,  4.31284757e-02,
         4.85132096e-02,  2.32036666e-01,  1.60516499e-01,
         2.75321798e-01, -7.82705280e-02,  7.93870967e-02,
         0.00000000e+00,  4.82875147e-02, -2.77555756e-17,
        -5.06360449e-01,  0.00000000e+00, -1.38777878e-17,
         0.00000000e+00,  4.86567121e-02, -2.77555756e-17,
         8.26734006e-02],
       [ 1.26300756e-02,  4.65530047e-02, -1.08765264e-02,
        -3.39053924e-02, -2.75453312e-03, -1.03680121e-01,
         0.00000000e+00, -8.54809031e-02,  5.42132389e-02,
         1.59110504e-02,  0.00000000e+00, -9.47223692e-02,
        -1.62911722e-02,  5.29322322e-02,  0.00000000e+00,
        -3.70037809e-02, -2.32235664e-02,  3.77009374e-02,
         2.21777191e-03,  7.22293798e-02,  7.19223344e-02,
         6.63571687e-02,  3.33809501e-02,  3.87855909e-02,
        -1.38751499e-01,  2.83077543e-02, -9.26590310e-02,
        -4.79172290e-02, -1.12008476e-01, -3.46944695e-18,
        -1.73472348e-18, -1.82576852e-02, -1.26160359e-01,
         1.81286074e-02],
       [ 1.47367753e-01,  4.69918358e-02,  2.61146957e-02,
         1.10396077e-01, -5.29833047e-02, -4.16333634e-17,
        -2.77555756e-17, -4.16333634e-17,  1.79892863e-01,
         1.64348484e-01, -2.77555756e-17, -2.77555756e-17,
        -2.55044070e-02,  1.70013658e-01, -2.77555756e-17,
        -1.39986473e-01,  1.03797290e-02,  1.53269224e-02,
         5.06432312e-02,  2.69788036e-01,  2.67460628e-01,
         2.69291464e-01,  6.51569098e-02,  1.28288764e-01,
        -2.77555756e-17,  9.77025281e-02, -2.77555756e-17,
        -2.04186327e-01, -4.16333634e-17, -2.08166817e-17,
        -6.93889390e-18, -9.22399782e-02, -1.38777878e-17,
         1.03690310e-01],
       [ 1.17157343e-01,  6.80858642e-02,  6.05184578e-02,
        -4.95972734e-02,  6.20640760e-02, -2.77555756e-17,
        -1.38777878e-17,  0.00000000e+00,  1.84478567e-01,
         1.47242261e-01,  2.77555756e-17,  2.77555756e-17,
         0.00000000e+00,  3.06988668e-01, -3.19530679e-01,
        -1.02292977e-02, -3.51314658e-02,  1.35393965e-01,
         1.32882369e-01,  1.70647361e-01,  9.82478208e-02,
         3.23450277e-01,  4.20198671e-02,  1.87840757e-01,
         0.00000000e+00,  4.35177529e-02,  2.77555756e-17,
        -6.44111237e-02,  0.00000000e+00, -1.61612778e-01,
         0.00000000e+00, -1.17867058e-01,  2.77555756e-17,
         1.00631112e-02],
       [ 5.56571211e-02,  3.94179687e-02,  3.15802964e-02,
        -1.35199049e-02,  1.10917316e-03, -6.93889390e-18,
        -1.69451033e-01, -6.93889390e-18,  2.58275779e-02,
         3.08091385e-02, -1.17526917e-01, -6.93889390e-18,
         0.00000000e+00,  7.53615229e-02, -1.38777878e-17,
        -1.09720653e-02, -4.02237908e-02, -1.98587047e-02,
         3.16210720e-02,  4.26339216e-02,  3.72509953e-02,
         1.21459155e-01,  4.27391464e-02,  7.29338416e-02,
        -6.93889390e-18,  3.15056055e-02, -6.93889390e-18,
        -8.55504679e-02, -1.38777878e-17, -2.14653121e-01,
        -1.97835448e-01,  3.56526238e-02,  1.82139306e-03,
         1.19914068e-01],
       [-9.56713676e-03,  5.81454159e-02, -3.91794128e-02,
        -3.67128509e-02, -2.41839491e-02, -1.26951584e-01,
         0.00000000e+00, -9.45188704e-02, -6.93889390e-18,
         1.57208784e-03,  0.00000000e+00, -1.53052144e-01,
        -5.77071513e-03,  4.33886001e-02,  0.00000000e+00,
        -8.12308274e-03, -4.94259986e-02, -1.67534588e-02,
        -4.67822566e-02,  0.00000000e+00,  1.76775824e-02,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -1.94786693e-01, -6.93889390e-18, -1.43486588e-01,
         8.03375070e-02, -1.43506029e-01,  0.00000000e+00,
         0.00000000e+00, -3.53970932e-02, -1.25438922e-01,
        -5.64925462e-04],
       [ 5.09965625e-01,  1.60641733e-01,  1.87595420e-01,
         9.03654557e-01, -1.48433222e+00,  0.00000000e+00,
         3.89919716e-01,  0.00000000e+00,  0.00000000e+00,
         2.20381716e-01, -4.44089210e-16,  0.00000000e+00,
         2.84563301e-01,  5.57201892e-01, -2.22044605e-16,
         3.01317813e-01,  1.77761972e-01, -2.38589373e-01,
        -3.43341435e-01, -4.44089210e-16, -8.88178420e-16,
         8.88178420e-16, -4.44089210e-16,  0.00000000e+00,
         0.00000000e+00, -1.79370448e+00,  0.00000000e+00,
         5.62878927e-01, -4.44089210e-16,  0.00000000e+00,
        -2.22044605e-16, -2.24031369e-01,  3.60945250e-01,
         1.93826284e-01],
       [ 6.49924802e-02,  1.04041085e-01,  1.85479854e-02,
         4.22847290e-02, -2.77555756e-17,  0.00000000e+00,
        -9.27990288e-02,  0.00000000e+00, -5.55111512e-17,
        -2.77555756e-17,  0.00000000e+00,  0.00000000e+00,
         1.51155204e-01,  1.69877684e-01, -4.21112784e-01,
         2.88742419e-01, -1.31838362e-01, -8.90815412e-02,
        -1.07033747e-02, -1.57539249e-02, -2.72736008e-01,
        -1.38423152e-02,  0.00000000e+00, -2.77555756e-17,
        -2.77555756e-17, -2.77555756e-17,  0.00000000e+00,
         4.91942418e-01, -2.77555756e-17, -3.18044271e-02,
         0.00000000e+00,  8.03536257e-03, -4.78792151e-02,
         2.26526081e-02],
       [ 2.16648235e-02, -2.52673854e-03,  3.51001900e-02,
         4.48610379e-03,  0.00000000e+00,  0.00000000e+00,
        -1.55902805e-01, -6.93889390e-18, -1.80381737e-02,
        -5.79698702e-02, -1.07454493e-01,  6.93889390e-18,
         5.18929233e-02,  7.05763977e-02,  6.93889390e-18,
         9.68740171e-02, -6.67415792e-03, -7.67191932e-02,
         8.35037199e-04, -6.29441553e-02, -4.03771958e-02,
         0.00000000e+00,  2.67499276e-02, -6.93889390e-18,
        -6.93889390e-18,  0.00000000e+00, -6.93889390e-18,
         9.06613943e-02,  0.00000000e+00, -1.76395553e-01,
        -1.89038299e-01,  5.10456631e-02,  2.53573633e-02,
         9.92419105e-02],
       [-7.01119543e-03, -2.81167062e-02,  2.24656040e-02,
         4.55751242e-02, -3.31200348e-02,  1.24386105e-01,
         0.00000000e+00,  1.13438589e-01,  6.93889390e-18,
         2.96067272e-02,  3.46944695e-18,  1.21141877e-01,
         1.83824219e-02,  6.93889390e-18,  0.00000000e+00,
         1.11810724e-02,  2.41826333e-02, -3.52711749e-02,
         3.28330474e-02,  6.93889390e-18,  1.38777878e-17,
         6.93889390e-18,  6.93889390e-18,  6.93889390e-18,
         1.89685626e-01, -2.30042582e-02,  1.29767919e-01,
        -2.31605940e-02,  1.62014355e-01,  0.00000000e+00,
         0.00000000e+00,  4.15843989e-03,  1.75386485e-01,
         5.49019481e-03],
       [ 1.99115248e-02, -1.28219250e-02,  4.37013485e-02,
         9.73621897e-03,  4.69496770e-02,  8.59446295e-02,
        -3.41795836e-02,  9.58763880e-02,  0.00000000e+00,
         1.80043842e-02,  3.46944695e-18,  1.11668398e-01,
         3.95965436e-02,  6.93889390e-18, -9.12521558e-02,
         9.31522821e-02,  2.03443205e-02, -3.10516497e-02,
         3.52244394e-02,  6.93889390e-18, -5.90445892e-02,
        -2.18994557e-03,  6.93889390e-18,  1.38777878e-17,
         1.57936911e-01,  6.93889390e-18,  1.11422089e-01,
         3.50173058e-02,  1.33740693e-01, -5.03167013e-03,
         3.46944695e-18,  7.56587895e-03,  1.33583593e-01,
        -1.14801548e-02],
       [ 2.06035726e-02, -2.90875135e-02,  3.75768803e-02,
         3.89530390e-02,  2.53722569e-02,  7.89129464e-02,
        -7.54797526e-02,  6.66007517e-02, -3.07838591e-02,
        -2.50147954e-02, -6.46791460e-02,  6.21228967e-02,
         1.84694117e-02,  0.00000000e+00,  0.00000000e+00,
         3.55171304e-02,  3.73001678e-03, -2.29446543e-02,
         3.55874034e-02, -2.86327153e-02, -2.60376061e-02,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         7.59798980e-02,  3.46944695e-18,  5.82498547e-02,
        -1.02627011e-02,  6.12917182e-02, -8.13970257e-02,
        -8.81232202e-02,  1.74630178e-02,  7.78797730e-02,
         6.09075437e-02],
       [-3.39379834e-02,  3.50333474e-02,  1.17897152e-01,
        -1.12025517e-01,  1.54682343e-01, -5.55111512e-17,
        -9.03537553e-02, -5.55111512e-17,  0.00000000e+00,
        -1.11022302e-16, -5.55111512e-17, -1.11022302e-16,
         4.62761874e-02,  1.72169664e-01, -5.53590521e-01,
         3.13373784e-01,  2.32895372e-02,  2.39791828e-02,
         9.68418635e-03, -9.97766113e-04, -3.65108127e-01,
        -3.96801667e-03, -1.11022302e-16, -5.55111512e-17,
        -5.55111512e-17,  1.10987426e-01, -2.77555756e-17,
         5.06099197e-01, -1.11022302e-16, -9.11700788e-03,
        -4.16333634e-17, -1.39441422e-01, -4.66175880e-02,
        -1.38655965e-01],
       [-1.52289856e-02, -4.03027244e-02,  1.67667326e-03,
        -2.42821749e-02,  3.54261108e-02,  6.93889390e-18,
        -1.76242940e-01,  0.00000000e+00, -5.09999960e-02,
        -5.53553289e-02, -1.51024497e-01,  6.93889390e-18,
         6.86458822e-03,  0.00000000e+00,  6.93889390e-18,
         5.39378713e-02, -1.00921023e-02, -1.12303574e-02,
         6.27013062e-03, -4.74361697e-02, -4.31368206e-02,
         6.93889390e-18,  6.93889390e-18,  6.93889390e-18,
         6.93889390e-18,  1.49731807e-02,  0.00000000e+00,
         2.78085118e-02,  0.00000000e+00, -1.67277053e-01,
        -2.05765055e-01,  3.01036137e-02,  6.93889390e-18,
         8.77356018e-02],
       [-1.68127447e-02, -4.09201667e-02, -3.87892769e-02,
         1.31106403e-02,  0.00000000e+00,  0.00000000e+00,
        -8.59039247e-02,  0.00000000e+00, -5.75513977e-02,
        -6.24662117e-02, -1.70424933e-01,  0.00000000e+00,
         0.00000000e+00,  1.38777878e-17,  1.29178209e-01,
         7.57587125e-03,  3.63035352e-02,  1.10510598e-02,
        -2.11446938e-02, -5.35297663e-02,  5.17932516e-02,
         2.86443327e-02,  0.00000000e+00,  6.93889390e-18,
         6.93889390e-18, -6.93889390e-18,  6.93889390e-18,
        -6.54545065e-02,  0.00000000e+00, -1.15124175e-01,
        -2.17769475e-01,  4.22452448e-02,  6.93889390e-18,
         1.54195019e-01]])

In [ ]:
# Convert to absolute values of coefs
import numpy as np
abs_coefs = np.abs(coefs)

In [ ]:
# Calculate the average imporatance across all classes
avg_importance = np.mean(abs_coefs, axis=0)

In [ ]:
# Extract the top 10% of features
num_top = int(0.10 * len(avg_importance))  # 10% of 34 = 3.4 → becomes 3
top_indices = np.argsort(avg_importance)[-num_top:]  # sorts and extracts the top 3

In [ ]:
# View top 3 as their original column names
top_features = X.columns[top_indices]
print("Top predictive features:", top_features.tolist())

Top predictive features: ['koebner phenomenon', 'disappearance of the granular layer', 'spongiosis']

In [ ]:
# Extract the top features into a new dataframe
X_top = X_scaled[top_features]
X_top.head()

   koebner phenomenon  disappearance of the granular layer  spongiosis
0           -0.699049                            -0.537770    1.813219
1            0.403761                            -0.537770   -0.844878
2            0.403761                            -0.537770    1.813219
3           -0.699049                             2.935592   -0.844878
4            1.506571                             1.777805    0.927187

In [ ]:
# Peform a new Train_Test_Split
X_train_top, X_test_top, y_train_top, y_test_top = train_test_split(
    X_top, y, test_size=0.2, random_state=33, stratify=y
)

In [ ]:
# Train first SVC model with a linear kernel and balanced class weight to compensate for class imbalance (Top 10% train_test_split)
svc_linear_top = SVC(kernel='linear', C=1, class_weight='balanced')
svc_linear_top.fit(X_train_top, y_train_top)

SVC(C=1, class_weight='balanced', kernel='linear')

In [ ]:
# Train second SVC model with a polynomial kernel and balanced class weight to compensate for class imbalance (Top 10% train_test_split)
svc_poly_top = SVC(kernel='poly', C=1.5, gamma=0.5, class_weight='balanced')
svc_poly_top.fit(X_train_top, y_train_top)

SVC(C=1.5, class_weight='balanced', gamma=0.5, kernel='poly')

In [ ]:
# Train third SVC model with a RBF kernel and balanced class weight to compensate for class imbalance (Top 10% train_test_split)
svc_rbf_top = SVC(kernel='rbf', C=0.5, gamma='scale', class_weight='balanced')
svc_rbf_top.fit(X_train_top, y_train_top)

SVC(C=0.5, class_weight='balanced')

In [ ]:
# Loop evalation metric print outs

# Define model name:object tuples
models_top = [
    ("Linear SVM Top 10%", svc_linear_top),
    ("Polynomial SVM Top 10%", svc_poly_top),
    ("RBF SVM Top 10%", svc_rbf_top)
]
# Iterate loop for metrics per model
for name, model in models_top:
    print(f"\n=== {name} ===")
    y_pred_top = model.predict(X_test_top)

    # Accuracy
    print(f"Accuracy: {accuracy_score(y_test_top, y_pred_top):.4f}")

    # Classification Report
    print("\nClassification Report:")
    print(classification_report(y_test_top, y_pred_top))

    # Confusion Matrix
    print("Confusion Matrix:")
    print(confusion_matrix(y_test_top, y_pred_top))

=== Linear SVM Top 10% ===
Accuracy: 0.6622

Classification Report:
              precision    recall  f1-score   support

           1       1.00      0.48      0.65        23
           2       0.69      0.92      0.79        12
           3       0.41      0.47      0.44        15
           4       0.71      1.00      0.83        10
           5       0.62      1.00      0.77        10
           6       0.00      0.00      0.00         4

    accuracy                           0.66        74
   macro avg       0.57      0.64      0.58        74
weighted avg       0.69      0.66      0.63        74

Confusion Matrix:
[[11  0 10  0  2  0]
 [ 0 11  0  0  1  0]
 [ 0  2  7  4  2  0]
 [ 0  0  0 10  0  0]
 [ 0  0  0  0 10  0]
 [ 0  3  0  0  1  0]]

=== Polynomial SVM Top 10% ===
Accuracy: 0.6351

Classification Report:
              precision    recall  f1-score   support

           1       0.92      0.48      0.63        23
           2       0.69      0.92      0.79        12
           3       0.35      0.40      0.38        15
           4       0.69      0.90      0.78        10
           5       0.69      0.90      0.78        10
           6       0.33      0.25      0.29         4

    accuracy                           0.64        74
   macro avg       0.61      0.64      0.61        74
weighted avg       0.67      0.64      0.63        74

Confusion Matrix:
[[11  0 10  0  2  0]
 [ 0 11  0  0  1  0]
 [ 1  2  6  4  1  1]
 [ 0  0  1  9  0  0]
 [ 0  0  0  0  9  1]
 [ 0  3  0  0  0  1]]

=== RBF SVM Top 10% ===
Accuracy: 0.6351

Classification Report:
              precision    recall  f1-score   support

           1       0.92      0.48      0.63        23
           2       0.69      0.92      0.79        12
           3       0.35      0.40      0.38        15
           4       0.69      0.90      0.78        10
           5       0.69      0.90      0.78        10
           6       0.33      0.25      0.29         4

    accuracy                           0.64        74
   macro avg       0.61      0.64      0.61        74
weighted avg       0.67      0.64      0.63        74

Confusion Matrix:
[[11  0 10  0  2  0]
 [ 0 11  0  0  1  0]
 [ 1  2  6  4  1  1]
 [ 0  0  1  9  0  0]
 [ 0  0  0  0  9  1]
 [ 0  3  0  0  0  1]]

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

For the final set of models, only the top 10% most predictive features were used, identified from the linear SVM's learned coefficients, to assess how well the models could perform with a reduced feature set. This step aimed to test whether a simpler, more interpretable model could still achieve competitive accuracy. While feature selection can reduce overfitting and improve model explainability, the results here showed a significant drop in performance.

- The Linear SVM had an accuracy score of 66.22%. Performance declined sharply compared to the full feature model. Class 1 recall dropped to 0.48 despite perfect precision, meaning over half of class 1 samples were misclassified. Class 6 wasn't predicted at all, and class 3 showed both weak recall and precision.

- The Polynomial SVM reached an accuracy of 63.51%, slightly lower than the linear model. It struggled with class 1 and class 3 in particular, and class 6 had both low recall (0.25) and precision (0.33). Misclassifications were spread across multiple classes, suggesting overfitting and poor generalization.

- The RBF SVM had an accuracy score of 63.51% and mirrored the polynomial model's metrics and confusion matrix exactly. This is likely due to the limited features available to train on and the similarities between the polynomial and RBF models.

Overall, these results demonstrate that reducing the feature set to only the top 10% significantly weakened the models' ability to distinguish between all 6 classes. While feature selection is valuable in some contexts, this task requires more than 10% of features to provide reliable performance.

---

## Conclusion
This investigation applied supervised machine learning techniques to a dermatology dataset for multiclass classification. The dataset included 34 features and 6 distinct diagnostic classes. Initial preprocessing involved filling missing values, standardizing all features using StandardScaler, and ensuring the target variable was in a compatible format. Three Support Vector Machine (SVM) classifiers, Linear, Polynomial, and RBF, were trained and evaluated across three different train-test splits. The first split used stratification to maintain class balance; the second intentionally omitted stratification to examine the impact of uneven class distribution; and the third reintroduced stratification to validate model performance under more controlled conditions. Across these nine models, the Linear and RBF SVMs consistently outperformed the Polynomial SVM, with the highest accuracy in the unstratified split reaching 98.65% with the RBF model; and 97.30% in the stratified linear model.

Additonally, the top 10% most predictive features based on the linear model's coefficients were selected and used to retrain all three models. These reduced-feature models showed significantly lower performance (around 63-66% accuracy), especially struggling with underrepresented classes like class 6.

Overall, the results demonstrate that full-feature models offer improved generalization compared to reduced-feature models. Additionally, though the unstratified models achieved slightly higher accuracy scores, those results were misleading due to the absence of rare classes like class 6 in the test set. The Linear SVM, trained on the first stratified split, provided the most reliable and balanced performance across all six classes, making it the best overall model in terms of generalization and fairness.